### ISSUE TITLE
Spurious location change events

### ISSUE THREAD

**Issue by acronce** [borski/ha-lucidmotors#14]
When I woke up this morning, I was surprised to find that the garage door was open. It turns out that at 4:12:15 AM my car's device location changed to "home", but it never left the garage. The location change fired off my automation to open the garage door, leaving it open. I got push notifications after 30 minutes (a separate automation), but didn't see them till I got up.

Checking the log book I see that the car was first reported as "not_home" at 12:12:15 AM, then at "home" almost exactly 4 hours later. Also just after the "home" event I see this one:

```
Lucid AIR Power state  changed to Cloud 2
```

Just in case I checked for other log events and none of the other doors or windows were opened. Also there were no camera event around these times.

Maybe what happened was a reset of some kind on the Lucid service side that generated the spurious not_home /home events?

I can work around this by making my automation smarter. I'm reporting the issue here in case there's something that could be done at the integration level to deal with Lucid service availability issues.

Note that I can't prove that there was a Lucid service issue. In the log file the only Lucid entry is this unrelated problem:

```
2024-02-19 14:30:48.211 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.lucidmotors.climate.LucidClimate'>) implements HVACMode(s): off, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/borski/ha-lucidmotors/issues
```

I can report the climate issue separately, if that helps.

**Comment by nshp** [comment]
Interesting. Can you add a Map Card to some dashboard, add the car to it, and set "hours to show" high enough that it includes that period? That'll show you a track of where its location was reported. I wonder if it jumped a _long_ way, like to the "default" location at Lucid HQ, or if it just jumped maybe a few feet outside your "home" bubble and back in.

The power state change is just the car periodically waking up (slightly) to ping out. It does this every 4 hours while idle I believe.

And yeah, please do report that climate issue separately, that looks like it should be an easy one to fix.

**Comment by acronce** [comment]
Thanks for the response!

I added the map card and the results are odd. Thirty seconds before the spurious "home" event the car was located on the street behind our garage. Eyeballing and using Google Maps measure, it looks to be about 285 feet away.

But the "not_home" event started 4 hours earlier. I don't see anything in the map view that shows that event. But it's kind of hard to identify individual events because they form a fuzzy mass near where the car is actually located. I assume that's just GPS fluctuations.

It's almost like the car is nowhere for 4 hours (like not on the map at all), then materialized 285 feet away, then came home. That 4 hour window seems to line up with the sleep time.

Here's the logbook entries (I wish these were easier to export or copy):

```
Lucid AIR Power state  changed to Sleep
4:17:15 AM - 11 hours ago
Lucid AIR Power state  changed to Cloud 2
4:12:15 AM - 11 hours ago
Lucid AIR  was detected at home
4:12:15 AM - 11 hours ago
Lucid AIR  was detected away
12:12:15 AM - 15 hours ago
Lucid AIR Power state  changed to Sleep
12:10:45 AM - 15 hours ago
```

Seems like it would not be possible for the car to have any location change events while sleeping. Maybe there's a way to filter out the spurious events.

In the meantime I have a work around in my automation where if an ultrasonic sensor says that the car is in the bay, it won't open the garage when the car "arrives". I might augment that further to not open the garage if the arrival event happens when the car is asleep. I mean, it can't sleep walk (er, sleep drive) ;-)

I'll make a separate card for the climate error.

**Comment by acronce** [comment]
Just a little more information to add. I looked at the automation trace for the "away" event that happened at 12:12:15 AM. It basically did nothing because my automation ignores the trigger if the garage door is closed. But there's still a record of it.

Looking at the changed variables view for the trace I can see in the `to_state` that the GPS coordinates match the location that's 285 feet away from the house. So the order of events seem to be:

1. The car goes to sleep.
2. The car is detected away (on the street behind us).
3. The car is detected at home.
4. The car wakes up.
5. The car goes back to sleep.

Note that we've had problems before when getting an Uber or Lyft where if we summon from inside the house, sometimes the driver goes to the street behind us. It hasn't happened recently though. Still, there seems to be some confusion with map systems out there in the world. Maybe something similar happened here.

To work around this for now I've augmented both my automations with a template condition so that location change triggers are ignored when the car is asleep. For example, here's the arrival automation:

```
alias: Garage open on arrival Lucid Air
description: Open the garage door when the Lucid air arrives at home.
trigger:
  - platform: zone
    entity_id: device_tracker.lucid_air
    zone: zone.home
    event: enter
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ states('sensor.lucid_air_power_state') != 'Sleep' }}"
      - condition: state
        entity_id: cover.garage_door
        state: closed
      - condition: state
        entity_id: binary_sensor.garage_middle_car_present
        state: "off"
action:
  - service: cover.open_cover
    metadata: {}
    data: {}
    target:
      entity_id: cover.garage_door
mode: single
```
