### ISSUE TITLE
Failed to contact Lucid cloud services

### ISSUE THREAD

**Issue by marschind** [borski/ha-lucidmotors#17]
I've run across a problem that manifests as my garage mysteriously opens sometimes while I am home.  I finally tracked it down to an automation script I got from Borski that basically says if my car enters the home zone, open the garage.  The problem is that sometimes when this integration tries to get the current status from Lucid, it gets an error.  When that happens, every sensor attached to the car goes to status "Unavailable", including the location.  The next time it polls, it gets the current status, and the location goes back to "Home", which causes the garage to open.  I haven't figured out how to modify the automation to track if the previous location was "Unavailable" to avoid opening the garage in this case, but perhaps a better solution is for the integration to not mark everything as Unavailable until some number of consecutive polls have failed.

**Comment by marschind** [comment]
Thanks.  That worked.

**Comment by borski** [comment]
For what it's worth, this was my automation:

```yaml
alias: Auto open garage door (Borski)
description: ""
mode: single
triggers:
  - entity_id: device_tracker.lulu
    zone: zone.home
    event: enter
    trigger: zone
conditions:
  - condition: state
    entity_id: cover.ratgdov2_1b599b_1b599b_door
    state: closed
actions:
  - metadata: {}
    data: {}
    target:
      entity_id: cover.ratgdov2_1b599b_1b599b_door
    action: cover.open_cover
```

So rather than checking for the state to change from `not_home` to `home` or from anything to `home`, I simply check if the car has entered the `home` *zone*. I haven't seen this screw up yet.
